version: '3'
services:
  schema-registry:
    image: bitnami/cp-schema-registry:${KAFKA_VERSION}
    hostname: schema-registry
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_DEBUG: 'true'
    networks:
      - ${GLOBAL_NETWORK:-kafka}
#Kafka Service
  kafka-1:
    image: "bitnami/kafka:${KAFKA_VERSION}"
    container_name: kafka-broker-1
    hostname: kafka-broker-1
    environment:
     - KAFKA_ENABLE_KRAFT=yes
     - ALLOW_PLAINTEXT_LISTENER=yes
     - KAFKA_CFG_NODE_ID=1001
     - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT

     - KAFKA_CFG_PROCESS_ROLES=broker,controller
     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1001@kafka-1:29092,1002@kafka-2:29093

     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,INTERNAL://kafka-1:19092
     - KAFKA_CFG_LISTENERS=CLIENT://:9092,CONTROLLER://kafka-1:29092,INTERNAL://:19092
     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL

    ports:
     - "9092:9092"
     
  kafka-2:
    image: "bitnami/kafka:${KAFKA_VERSION}"
    container_name: kafka-broker-2
    hostname: kafka-broker-2
    environment:
     - KAFKA_ENABLE_KRAFT=yes
     - ALLOW_PLAINTEXT_LISTENER=yes
     - KAFKA_CFG_NODE_ID=1002
     - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT

     - KAFKA_CFG_PROCESS_ROLES=broker,controller
     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1001@kafka-1:29092,1002@kafka-2:29093

     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9093,INTERNAL://kafka-2:19093
     - KAFKA_CFG_LISTENERS=CLIENT://:9093,CONTROLLER://kafka-2:29093,INTERNAL://:19093
     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL

    ports:
     - "9093:9093"
     
  kafka-3:
    image: "bitnami/kafka:${KAFKA_VERSION}"
    container_name: kafka-broker-3
    hostname: kafka-broker-3
    environment:
     - KAFKA_ENABLE_KRAFT=yes
     - ALLOW_PLAINTEXT_LISTENER=yes
     - KAFKA_CFG_NODE_ID=1003
     - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT

     - KAFKA_CFG_PROCESS_ROLES=broker
     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1001@kafka-1:29092,1002@kafka-2:29093

     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9094,INTERNAL://kafka-3:19094
     - KAFKA_CFG_LISTENERS=CLIENT://:9094,INTERNAL://:19094
     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
     
    ports:
     - "9094:9094"
     
    depends_on:
      - "kafka-broker-2"
      - "kafka-broker-3"

  kafdrop:
    image: 'obsidiandynamics/kafdrop:3.32.0-SNAPSHOT'
    restart: "no"
    ports:
      - 9000:9000
    
    environment:
      - KAFKA_BROKERCONNECT=kafka-broker-1:19092,kafka-broker-2:19093,kafka-broker-3:19094
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    
    container_name: kafdrop
    depends_on:
      - "kafka-broker-1"
      - "kafka-broker-2"
      - "kafka-broker-3"